name: Run tests

on:
  push:
  pull_request:
  schedule:
      - cron: '0 8 * * *'

jobs:
    php-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                php: [5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0]
                laravel: [5.4.*, 5.5.*, 5.6.*, 5.7.*, 5.8.*, 6.*, 7.*, 8.*]
                version: [prefer-lowest, prefer-stable]
                os: [ubuntu-latest]
                include:
                    - laravel: 5.4.*
                      testbench: 3.4.2
                    - laravel: 5.5.*
                      testbench: 3.5.*
                    - laravel: 5.6.*
                      testbench: 3.6.*
                    - laravel: 5.7.*
                      testbench: 3.7.*
                    - laravel: 5.8.*
                      testbench: 3.8.*
                    - laravel: 6.*
                      testbench: 4.*
                    - laravel: 7.*
                      testbench: 5.*
                    - laravel: 8.*
                      testbench: 6.*
                exclude:
                    - laravel: 5.5.*
                      php: 5.6
                    - laravel: 5.6.*
                      php: 5.6
                    - laravel: 5.6.*
                      php: 7.0
                    - laravel: 5.7.*
                      php: 5.6
                    - laravel: 5.7.*
                      php: 7.0
                    - laravel: 5.8.*
                      php: 5.6
                    - laravel: 5.8.*
                      php: 7.0
                    - laravel: 6.*
                      php: 5.6
                    - laravel: 6.*
                      php: 7.0
                    - laravel: 6.*
                      php: 7.1
                    - laravel: 7.*
                      php: 5.6
                    - laravel: 7.*
                      php: 7.0
                    - laravel: 7.*
                      php: 7.1
                    - laravel: 8.*
                      php: 5.6
                    - laravel: 8.*
                      php: 7.0
                    - laravel: 8.*
                      php: 7.1
                    - laravel: 8.*
                      php: 7.2

        name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.version }} - ${{ matrix.os }}

        steps:
            - name: Checkout code
              uses: actions/checkout@v2

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
                  coverage: none
                  tools: composer:v2

            - name: Install dependencies
              run: |
                composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                composer update --${{ matrix.version }} --prefer-dist --no-interaction

            - name: Execute tests
              run: vendor/bin/phpunit

